language: node_js
env:
  CI: ''
before_script:
- npm install
node_js:
- 12
script:
- npm run build:client
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: AKIA5RGKFL34F5A5KYHN
  secret_access_key:
    secure: hGd4kg9mTP+PkN3vPXUjYAPzASSMctg2kiDY7yAJ01XKW64agU0BiWrVbxXd/jzUXMGSSoeHnXkPTeAMOyKq8cNt3eE2+3+Xq169Kc9QpFfxDZwvrBTnnFYLpT3WQDIz2KSKxMJWoV8Ywozub7r/nDe1iudkry6jmaURqqGl0K0fUj3tAdyCIPF8vNW0oMVgyt07zj3AVY+20BTNAtNaOmiHCuAZKMeTD0yJHP/yEi7VhcSJONiXg1otYah4MglrejwAo8A4qLfYoEzgyIoSVR/RSanSlCqs0C8Sa/d71HIzJCSYYPvrjRXJhQ0pnnJf/MIqvW0oKxahmzumKfIDosUGudqPAEEPhwI0pkzaXCZ3RDPWvkazznyqHFU+2+qX2Rgh0WJzKJL551+75eRqf3Pk34x820oXAShuGH1cK55IzssERRVwYYIxCDJVKBNWaat0Jm9AoOxjx24CPoTAi2TE/EgVVBrRFMJV3e5BmzS2T17hY3LCeihZDxOOydlPhaycv2niBlwCfPJCskQXI4YG5uBJCUaXiiIB3ZnWrj7C7yOL8KU7e6HKpFEa0hcw6j4pN/JGlKkyukwB7Og6EBLFBPJeyKOOXl7mR7dcyXM9d+VF49WDwizGj2gsv93l8wcrlSFVkssJvktk7icUZG3a5wy9AQQrE2WIilXzGK4=
  application: app0
  deployment_group: travis
  region: us-east-1
