language: node_js
env:
  CI: ''
before_script:
- npm install
node_js:
- 12
script:
- npm run build:client
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: "AKIA5RGKFL34J2JMXKFM"
  secret_access_key:
    secure: "v35gq7tzjSMA3dSzbQsWq0aJUw4cOiMPVjMsTMyKy5bWbbKRyNpKZSJCPjGNJYVKNKwWc1ZZnZBOmj2hamRht5ymBGvvfT0b2PgfcsO/qgsd6wqumAiIACdmEZJXNjkBT1kv1qnWPGYpB7UawTuZ3/gSAUEcTCZ55Y/GwWpCJ5B72nNNcdi3aWInhTjhN+kbilmcsrVd1ghJH45GtaLE1X3EcaCB0PkhKPyVZxRDLzypiG9d4FS6obNABdPfUCShpWtuvIgrYk3X1gyQXmYpmPj/Svg7I0gsMVlP+R4stFh2RVP8N+OgWIAwWsbHc4Wj/ej23S6b8iSPg3+DwKB5w5JhFE+RiTiDxwdrOEHPqV9s/wwywJEv0QRv1T1vOF9feXVd4rLsegzo2bwd1W2Fj5sHRFb0VjPTzLnK048SW9M/PqErLuL8j8kzNN0zsSRIC6N3mg+i3VowULyrcQDzBXkACTN+EsTCWD+lItmyHjHwlmULM/0EcEfZUFhQNsXh4utKy1wetrRFaLbPii2Ion/4QfgdoypjYFVTNWHLhw8TwGX9nwFkMdnL+2QxXUJuWVyJUw/K4YrmteGtbwF2Ph2lYWpZmIhEA3DNVUpzsPDoPKndy2FZflCLdsPS9bldn0NzeTlnGRX3wP8i1pdC+CDhil7p1Z0GbZPgjJqSOQM="

  application: app0
  deployment_group: group0
  region: us-east-1
