language: node_js

env:
    CI: ""

before_script:
  - npm install

node_js:
  - 13
  - 12

script:
  - npm run build:client

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: AKIA5RGKFL34LURUFMNY
    secret_access_key: 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
    application: "app0"
    deployment_group: "travis"
    region: "us-east-1"
