language: node_js
env:
  CI: ''
before_script:
- npm install
node_js:
- 12
script:
- npm run build:client
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: AKIA5RGKFL34J2JMXKFM
  secret_access_key:
    secure: "sKEsoM/GLMyktT9XhS0obXCcW54SgMoXDak9GsBFmWmr86UNQpeNO95ulQNVqTrDKxymk5qZWd1/R+96OqCym279kI2lvn2MBR5UW9lNGW0JjfYGayJDiJ9nbqcGFV7aaG62bifR67tqunD6DRm4c/m+Rt1jLfMdXIidiie8QCdmgl+NFKjlfC1hcwYhAwVuzapK8Oyd9wW1Bt/nZu+CPk7HLakMwiL5N5XqfN5L/jFmdoPeseqA68L0WPcqpFbuarWQtTs8fnP3tWibGTlDaFCeqaBsqpXpeRCp3p57PIc4803ebPUvGpB5DF7gojZWMHgTaNnIwuf+NR7PdWIjBrzS4/9uF8ETMfZeyVWVpqqtkfODUCK147e3EASFkkmtVDEY8MlnOsnCbanakn2VUbi0rLDnp+sLSOnn6ZuTJPnUXv1+ayI8dZZMFYlyDKEO/6u8ss6gsDMhoRqmtlnqP0JwTliEcWRCguXYEfbx297ahuwNM2n6kWV8IN+9MDAS/BzH2jKiXejuqL99f8tv4IcVE4QaqHgwjUpAMJ14i8jd6pBtCQQx8tLRZqOtzS8dRtvZ2DLaxiC8QleptcFSMklq7pVGGwwjkvpFb1jCld0h4zAYy7wmIsaN9aOhNtRIJeuNW230ABQCncJj2ucBMel1CUq3xtxkCNhrRaIhZ68="
  application: app0
  deployment_group: group0
  region: us-east-1
