language: node_js
env:
  CI: ''
before_script:
- npm install
node_js:
- 12
script:
- npm run build:client
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: "AKIA5RGKFL34J2JMXKFM"
  secret_access_key:
    secure: "o1oxOSMYQEhKok/A8tESDLhvMVioaKHiiLrmTKP+RbxW7rR5mTu865gcztcZYwkcV8os0HHQnj7S3gFE7sm6pwiOG17QX7t7vfDaBLA0zSNWsJcgJITFmk5Ew8sQZ7q4wZWeUXYSqfq19oc7hKRj2Y/HnG5YRdUUZwxXEpwOhSv/wB+6beFLkyVWFCenESf0fRJ7ouZHu7zd1ZARVmKer6zDYB5VvJ94hC5sZz7kfG2PG4x0nEduGU/vDBTNOwNHBNn8p01eT/TRJdz8pZkWIG8AjmEZNLf+bcUO5qvdAMNzsPWDeJEv8ROksieAjs0MctMJK1uNrEYUSdRXkQcmhEF3AOXPaGfjtJgFeG8LjlNrxOFdoFCWozqWKEQJVzYEG4hN/ulcQRnUTDiFeLWRUPCrupkhnzrrQ8G4BrlJPcejIp8MB0P85TIkdJd6wKpxI6z/eDnvwcrEEKyXLoIytcFFGC4h0kNppsQtIfYWVy1+E9osUPyTMb3SWf6RP4ZBydgFSAZ3otRueb44gUoP79jQHSxDn87l1H6a0gZz2UlwtTMGuUXpr5zJyHhkhLDXkxp3oOmUmUAGpRA9hiSFZQJnT+5jWlwJo5vqYIRKmArSStLSJ06R2PizImuZO6gBaEABUwb62Ov12dcTOwuevxOsC4Iv5r+wV5weVs9N6Fc="

  application: app0
  deployment_group: group0
  region: us-east-1
