language: node_js
env:
  CI: ''
before_script:
- npm install
node_js:
- 12
script:
- npm run build:client
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: AKIA5RGKFL34J2JMXKFM
  secret_access_key:
    secure: "MHVDlVp5KiM4fwFOd6myG+CbmN8OPaKDMUGpDjoskizlFLvlUtrBlKOeFaK4GVBExVDg/j44df8WXkdPDIHRveo8H50mHi/ZXWFVW3LKFuBEUwCPdDYnRO80j3v35E65vejrQ0CO3MINsZteaoYimIVabcWoeT8Sum/Eso84Jo6N1qvtVs0ZYxazhY8oOmJI5D91svn0fAiifupymaSEr6C7uwGdCZrEQkbROJNcG8+hWHH7FimHuVJZSszswRix1ad00Mrw5IDJZgzpIMuB9EtPEgcnRDmVHRKVodYwCvwCjbvLtmhD4cASFOzxrueOmaMM+ZuyplFOLH5JuM8o5kfSyH3Xn2Ls/QI1iQRVJAJU26f4Ys19tcSWH2oZXRSBiY7eiYqAUVMgySHFX7MpNh5/FqbvBwLNhSggyM1qBZf8K4Z/JQkfTlVcFGjOmPjJ3813LlIDMNfKOLXAhl4+zt2batMvFCjsyrnC505h1JbkfIiVrH4H2cwDDDVX0Af+FzDVc+rLQbl+atKaLoF2xFHkcXpwJfd3Bb1BKMutKUKxmSHp/b+alU0WrrJJyo6o65UZsBhXCCL9fTmPX8TtVEdGQ9Yid2XrOFSDu4acnQfqL6iF2TWg2nU3GtW60eGo2kr5OW7LK4OcZhjmD9pGvhmG5hi7vFmnKSgQd01xAbk="
  application: app0
  deployment_group: group0
  region: us-east-1
