language: node_js
env:
  CI: ''
  global:
    secure: y+IQE9fklROEd0fQjfSCR7jCF8zY1uLiC0z0Hcf9sx6WjiB4z6uSVBXxQGluQdI0iGoH2DG3FT21Nh/Ath5VOfWpd4wA9D8kUDwgkSEod3++0LaOjYdVpYrsFKRnMglbDn7u3QQP3+poFtJQO4Ztu8hlWvUwaUCb0v21y7WyjyQwv/OXXCACFRZit14F8Ll5yOVXC9UUaU5Z3ZOaxhRyMa3Fr4Qxxdwao4fah7wOINybgmcgPe5xrZGVEp15pn6kO1OmvIjci6bNnWmJpLMxBvH+AbXNe67Fb8K7WA+KumpW5tRgU67bDyHBah7KZJQ6ILvgGoHr8wv3+l2G7H7bp34PVEsL/zNL5P+XfNogm0K2+WJAHGrZDgWevLP1sZz/0Xk5SEj0bePRKZ+K5Dcmnj8ZmdDxbwj2/gIhxr8nwV0IspEDo+Mb56g8Od68epuV/QEJehg65DXx90dRu2P8QOiD9uUepX8SQvHAfhmFB4ZJwjsNeu8bzFoLlHS/lAKFB0KbRUshzqOBw3CegpCKW19A5PXZyWC7i2M6PPGSNlnJv+m8wv6z1dEv10bIDmt+b7FV/XNfN4wX525dIHdiv8ctYytrfo2n2OTUDUMLc/Wgn00XBW3/Ui+YcB7n+oWFGqMbYZh6c22rPL7sdRjbrHQ90hgYoQ7shS6peCWHVzs=
before_script:
- npm install
node_js:
- 12
script:
- npm run build:client
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: AKIA5RGKFL34J2JMXKFM
  application: app0
  deployment_group: group0
  region: us-east-1
